# Page settings
baseurl = "https://ruzekklein.github.io/development-and-design/"
title = "Web Design Cooperative"
languageCode = "en-us"
theme = "hugo-elate-theme"

[params]
  
  custom_css = ["css/custom1.css", "css/custom2.css"]

  # Meta
  author = "Web Design Cooperative"
  description = "Choose your own custom web and graphic package to build your business or project. The Web Design Cooperative will connect you with the development and design to achieve your goals."
  email = "amelia.ruzek.klein@gmail.com"
  # Navigation
  [params.navigation]
    brand = "Web Design Cooperative"
    home = "Home"
    work = "Work"
    testimonials = "Testimonials"
    services = "Services"
    about = "About"
    contact = "Contact"

    # You can add custom links before or after the default links
    # Assign a weight to define the order
    
    # prepended links
    #[[menu.prepend]]
    #  url = "http://gohugo.io"
    #  name = "Hugo"
    #  weight = 10

    # postpended links
    #[[menu.postpend]]
    #  url = "http://gohugo.io"
    #  name = "External link"
    #  weight = 10
  
  # Hero section
  [params.hero]
    title = "Choose your own custom web and graphic package to build your small business or project."
    subtitle = "The Web Design Cooperative will connect you with the development and design to achieve your goals."
 
  # Intro section
  # Available icons: http://simplelineicons.com/
  [params.intro]

  [[params.intro.item]]
    title = "Simple. Organized."
    description = "Includes unlimited email consultations with a professional web designer, two concept wireframes, a scrolling one page HTML5 responsive website with high quality stock photography or your own images, and one revision."
    url = "#"
    button = "$500"
    icon = "icon-picture"
    img = "img_7.jpg"

  [[params.intro.item]]
    title = "Innovative. Beautiful."
    description = "Includes unlimited email consultations with a professional web designer, three concept wireframes, a multi-page interactive HTML5 responsive website with high quality stock photography or your own images, and two revisions."
    url = "#"
    button = "$1200"
    icon = "icon-energy"
    img = "img_8.jpg"

  [[params.intro.item]]
    title = "Unique. Magnificent."
    description = "Includes face-to-face consultations with a professional web designer, three concept wireframes, a multi-page interactive HTML5 responsive web experience with high quality stock photography or your own images, a custom built user interface, and two revisions."
    url = "#"
    button = "$2500"
    icon = "icon-rocket"
    img = "img_10.jpg"

  [params.intro.video]
    enable = false
    title = "Watch the video"
    icon = "icon-play2"
    url = "https://vimeo.com/channels/staffpicks/93951774"


  # Work section
  [params.work]
    enable = true
    title = "Work"
    description = "Whether your project is a hobby or a fortune 500 campaign, we've got you covered."
    footertext = ''

    [[params.work.row]]
      img = "work_1.jpg"
      alt = "a wireframe displaying various templates"
      title = "Modular Web Templating"
      subtitle = "Photoshop, Sketch, Zeplin"

    [[params.work.row]]
      img = "work_2.jpg"
      alt = "a logo in the shape of wisconsin"
      title = "Branding"
      subtitle = "Illustrator, Animation, SVG"

    [[params.work.row]]
      img = "work_3.jpg"
      alt = "a website displaying a modular gallery"
      title = "Development"
      subtitle = "HTML5, CSS, jQuery, JSON"

  # Testimonials section
  [params.testimonials]
    enable = true
    title = "Testimonials"
    description = "Read what our clients have to say."

    [[params.testimonials.item]]
      quote = "&ldquo;Easy to work with and great finished project.&rdquo;"
      person = 'Andy R. Bunch<span class="subtext">Author</span>'
      img = "person1.jpg"
      alt = "Person1"

    



  # Services section
  [params.services]
    enable = true
    title = "Services"
    description = ""

    [[params.services.item]]
      title = "Brand &amp; Design"
      description = "Need a logo, newsletter, or an invitation design? No problem - contact us with more information about the project and we can provide custom pricing."
      icon = "icon-anchor"

    [[params.services.item]]
      title = "Web &amp; Interface"
      description = "This is our specialty! Take a look at the packages above or work with us to customize your own web package. We can even advise with CMS and domain services."
      icon = "icon-layers2"
      
    [[params.services.item]]
      title = "Photoshop &amp; Animation"
      description = "Do you need photos altered, video editing, or audio help? Maybe you need a neat GIF for your social channel? Look no further. We're here to help."
      icon = "icon-camera"

    [[params.services.item]]
      title = "Automation Solutions"
      description = "I bot. You bot. Let's bot together. Make things easier - make things faster - with a bot that does it for you. <a style = 'color: black' href='https://en.wikipedia.org/wiki/Software_agent'>Learn more about bots.</a>"      
      icon = "icon-monitor"

  # About section
  [params.about]
    enable = true
    title = "About"
    description = ""

    [[params.about.item]]
      name = "Amelia Ruzek Klein"
      position = "Web Designer & Developer"
      description = "I’m Amelia Ruzek Klein, designer, developer, and founder of the Web Design Co-op. I have 6+ years experience working with clients ranging from small hobbyists to fortune 500. I have a B.A. in Graphic Design and I’m working toward an M.L.A. in Digital Media Design. You can trust your project is in good hands."
      alt = "image of Amelia"
      social = [
        ["icon-twitter", "#"],
        ["icon-facebook", "#"],
        ["icon-linkedin", "#"]
      ]


  # Counters section
  [params.counters]
    enable = false
    title = "Stats"
    background = "full_image_1.jpg"

    [[params.counters.item]]
      description = "Finished projects"
      icon = "icon-briefcase"
      from = 0
      to = 89
      interval = 50
      speed = 5000

    [[params.counters.item]]
      description = "Lines of code"
      icon = "icon-code"
      from = 0
      to = 2343409
      interval = 50
      speed = 5000

    [[params.counters.item]]
      description = "Cups of coffee"
      icon = "icon-cup"
      from = 0
      to = 1302
      interval = 50
      speed = 5000

    [[params.counters.item]]
      description = "Happy clients"
      icon = "icon-people"
      from = 0
      to = 52
      interval = 50
      speed = 5000

  # Contact section
  [params.contact]
    enable = true
    map = false
    title = "Get in touch"
    # description = ""
    
    # Available icons: http://simplelineicons.com/
    # details = [
    #    ["icon-home", "5555 Love Paradise 56 New Clity 5655, <br> Excel Tower United Kingdom"],
    #    ["icon-phone", "(123) 465-6789"],
    #    ["icon-envelope", "info@freehtml5.co"],
    #    ["icon-globe", '<a href="http://freehtml5.co/" target="_blank">freehtml5.co</a>']
    #  ]

    name = "Name"
    email = "Email"
    phone = "Phone"
    message = "Message"
    button = "Send message"

  # Footer section
  [params.footer]
    enable = true
    copyright = '&copy; Web Design Cooperative. All Rights Reserved.'
