# Site settings
baseurl = "https://ruzekklein.github.io/development-and-design/"
languageCode = "en-us"
title = "Ruzek-Klein Development & Design"
publishDir = "docs"


[params]

    # You can use Markdown syntax for urls [text](//url.to/source) for
    # most longer texts.

    # To provide some metadata for search engines feel free to add a few
    # information about you and your website.
    name = "Ruzek-Klein Development & Design"
    description = "I specialize in creating websites and graphics that meet your business or project needs. Choose your own customizable package to get up and running in no time."

    # Since this template is static, the contact form uses www.formspree.io as a
    # proxy. The form makes a POST request to their servers to send the actual
    # email. Visitors can send up to a 1000 emails each month for free.
    #
    # What you need to do for the setup?
    #
    # - set your email address under 'email' below
    # - upload the generated site to your server
    # - send a dummy email youself to confirm your account
    # - click the confirm link in the email from www.formspree.io
    # - you're done. Happy mailing!
    email = "amelia.ruzek.klein@gmail.com"

    # Custom assets
	custom_css = []
	custom_js  = []

    [params.navigation]
        brand = "Ruzek-Klein Development & Design"


    [params.header]
        # Copy your own image into './static/img/'' if you wish
        name = "Choose your own customizable web and graphic package to build your small business or project."
        subtitle = "I'm Amelia Ruzek-Klein, developer and designer."


    [params.portfolio]
        # All projects defined in their own files. You can find example projects
        # at 'exampleSite/data/projects'. Copy the 'projects' folder into the 'data' directory
        # at the root of this Hugo site.
        # For more informtion take a look at the README.
        title = "Portfolio"

        [params.portfolio.modal]
            client = "Client"
            date = "Date"
            category = "Category"
            buttontext = "Close"


    [params.about]
        title = "About"
        # The about text is splitted into a left and right column
        left = "I have 6+ years experience working with clients ranging from small hobbyists to fortune 500. I have a B.A. in Graphic Design and I'm working toward an M.L.A. in Digital Media Design. You can trust your project is in good hands."
        right = "Whether you're a student needing to showcase your work, a professional looking to attract clients, or a small business ready to grow, Ruzek-Klein Development and Design is the perfect starting point!"

        [params.about.button]
            text = "Get started today"
            link = "#contact"
            icon = ""


    [params.contact]
        title = "Contact"

        # 'error' defines error messages for invalid inputs
        [params.contact.form.name]
            text = "Name"
            error = "Please enter your name."

        [params.contact.form.email]
            text = "Email Address"
            error = "Please enter your email address."

        [params.contact.form.phone]
            text = "Phone Number"
            error = "Please enter your phone number."
            
        [params.contact.form.price]
            text = "Would you like to negotiate pricing? Message me."
            error = "Please select at least one service"
            
        [params.contact.form.service]
        
            [params.contact.form.service.website]
            text = "Website"   
            id = "service-website"
            price = "100"
            extra = " (one page)"
            
            [params.contact.form.service.hosting]
            text = "Hosting"   
            id = "service-hosting"
            price = "100"
            extra = " (per year)"
            
            [params.contact.form.service.domain]
            text = "Domain Name"   
            id = "service-domain"
            price = "20"
            extra = " (per year)"
            
            [params.contact.form.service.interactive]
            text = "Interactive Web Component"   
            id = "service-interactive"
            price = "100"
            extra = " (one calculation, animation, map, gallery, form, etc...)"
            
            [params.contact.form.service.application]
            text = "Web App"   
            id = "service-application"
            price = "800"
            extra = " (user information is saved)"
            
            [params.contact.form.service.cms]
            text = "Content Managed Website"   
            id = "service-cms"
            price = "50"
            extra = " (ex: squarespace, wix, wordpress, shopify, weebly etc. plus cost of platform ($0 - $500/yr))"
            
            [params.contact.form.service.webrevision]
            text = "Web Revision"   
            id = "service-webrevision"
            price = "50"
            extra = " (each)"
            
            [params.contact.form.service.touchup]
            text = "Photo Touch-up or Effect"   
            id = "service-touchup"
            price = "25"
            extra = " "
            
            [params.contact.form.service.replace]
            text = "Photo Remove/Replace Background"   
            id = "service-replace"
            price = "10"
            extra = " "
            
            [params.contact.form.service.gif]
            text = "GIF Animation"   
            id = "service-gif"
            price = "30"
            extra = " "
            
            [params.contact.form.service.resize]
            text = "Resize Photo"   
            id = "service-resize"
            price = "10"
            extra = " "
            
            [params.contact.form.service.change]
            text = "Change File Type"   
            id = "service-change"
            price = "10"
            extra = " (ex: jpg logo to vector logo)"
            
            [params.contact.form.service.photorevision]
            text = "Photo Revision"   
            id = "service-photorevision"
            price = "5"
            extra = " (each)"
            
            [params.contact.form.service.ad]
            text = "Advertisement"   
            id = "service-ad"
            price = "50"
            extra = " (printing not included)"
            
            [params.contact.form.service.poster]
            text = "Poster"   
            id = "service-poster"
            price = "50"
            extra = " (printing not included)"
            
            [params.contact.form.service.logo]
            text = "Logo"   
            id = "service-logo"
            price = "50"
            extra = " "
            
            [params.contact.form.service.invitation]
            text = "Invitation"   
            id = "service-invitation"
            price = "50"
            extra = " (printing not included)"
            
            [params.contact.form.service.businesscard]
            text = "Business Card"   
            id = "service-businesscard"
            price = "25"
            extra = " (printing not included)"
            
            [params.contact.form.service.letterhead]
            text = "Letterhead"   
            id = "service-letterhead"
            price = "25"
            extra = " (printing not included)"
            
            [params.contact.form.service.tshirt]
            text = "T-Shirt"   
            id = "service-tshirt"
            price = "25"
            extra = " (screen printing not included)"
            
            [params.contact.form.service.digitaldesign]
            text = "Web or App Design"   
            id = "service-digitaldesign"
            price = "50"
            extra = " (one page. mocks/specs only. development not included)"
            
            [params.contact.form.service.designrevision]
            text = "Design Revision"   
            id = "service-designrevision"
            price = "10"
            extra = " (each)"
            
            [params.contact.form.service.consultationemail]
            text = "Consultation via Email"   
            id = "service-consultationemail"
            price = "10"
            extra = " (unlimited)"
            
            [params.contact.form.service.consultationperson]
            text = "Consultation in Person"   
            id = "service-consultationperson"
            price = "25"
            extra = " (one hour)"
            
            [params.contact.form.service.bot]
            text = "Software Task Automation"   
            id = "service-bot"
            price = "100"
            extra = " (content migration, social media auto posting, etc...)"
            
            [params.contact.form.service.idea]
            text = "Idea Sketches"   
            id = "service-idea"
            price = "5"
            extra = " (each)"

        [params.contact.form.message]
            text = "Message"
            error = "Please enter a message."

        [params.contact.form.button]
            text = "Send"


    [params.footer]
        copyright = "Published under the Apache License 2.0. Powered by [Hugo](//gohugo.io)."

        [params.footer.location]
            title = "Location"
            # Postal address (add as many lines as necessary)
            address = ["Stevens Point, Wisconsin"]

        [params.footer.social]
            title = ""
            # All icons using Fontawesome's icon font. Look at fortawesome.github.io/Font-Awesome/icons/
            # for more icons. The icons are represented by their corresponding
            # CSS class.
            


        [params.footer.credits]
            title = ""
            text = ""
